server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
# 连接码云远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gip_jun/spring-cloud-config.git  # 注意是https的而不是ssh
          # 通过 config-server可以连接到git，访问其中的资源以及配置~

# 不加这个配置会报Cannot execute request on any known server 这个错：连接Eureka服务端地址不对
# 或者直接注释掉eureka依赖 这里暂时用不到eureka
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

eureka:
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心


